/**
 * Checks the committed public/data/cities.json (generated by
 * scripts/build-cities.py). City names do not expire, so this is stable.
 */
import { existsSync, readFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { cityHit, decodeCities, searchCities } from './city-index';

const PATH = resolve(process.cwd(), 'public/data/cities.json');
const present = existsSync(PATH);

describe.skipIf(!present)('public/data/cities.json', () => {
  const raw = present ? readFileSync(PATH) : Buffer.from('');
  const index = present ? decodeCities(JSON.parse(raw.toString('utf8')))! : null;
  const top = (q: string) => searchCities(index, q, 6).map(cityHit);

  it('meets the size budget and carries the GeoNames licence', () => {
    expect(raw.length).toBeLessThanOrEqual(2_000_000);
    expect(gzipSync(raw).length).toBeLessThanOrEqual(700_000);
    const file = JSON.parse(raw.toString('utf8'));
    expect(file.license).toBe('CC BY 4.0');
    expect(file.attribution).toBe('GeoNames (geonames.org)');
    expect(index!.rows.length).toBeGreaterThan(20_000);
  });

  it('finds Seville for sevil, Sevilla and séville, not served by AC', () => {
    for (const q of ['sevil', 'Sevilla', 'séville', 'Séville']) {
      const [hit] = top(q);
      expect(hit.place.id, q).toBe('gn-2510911');
      expect(hit.place.name).toBe('Seville');
      expect(hit.place.country).toBe('Spain');
      expect(hit.servedBy).toBeNull();
    }
  });

  it('finds Lisbon for lisboa (served by LIS), Montréal for montreal, Kraków for krakow', () => {
    const [lis] = top('lisboa');
    expect(lis.place.name).toBe('Lisbon');
    expect(lis.servedBy).toBe('LIS');
    expect(top('montreal')[0].place.name).toBe('Montréal');
    expect(top('krakow')[0].place.name).toBe('Kraków');
  });
});
