const COUNTRY_FLAGS: Record<string, string> = {
  'Algeria': '🇩🇿',
  'Antigua & Barbuda': '🇦🇬',
  'Argentina': '🇦🇷',
  'Aruba': '🇦🇼',
  'Australia': '🇦🇺',
  'Austria': '🇦🇹',
  'Azores': '🇵🇹',
  'Bahamas': '🇧🇸',
  'Barbados': '🇧🇧',
  'Belgium': '🇧🇪',
  'Belize': '🇧🇿',
  'Bermuda': '🇧🇲',
  'Brazil': '🇧🇷',
  'Canada': '🇨🇦',
  'Cayman Islands': '🇰🇾',
  'Chile': '🇨🇱',
  'China': '🇨🇳',
  'Colombia': '🇨🇴',
  'Costa Rica': '🇨🇷',
  'Cuba': '🇨🇺',
  'Curaçao': '🇨🇼',
  'Czech Republic': '🇨🇿',
  'Denmark': '🇩🇰',
  'Dominican Republic': '🇩🇴',
  'Ecuador': '🇪🇨',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Greece': '🇬🇷',
  'Grenada': '🇬🇩',
  'Guadeloupe': '🇬🇵',
  'Guatemala': '🇬🇹',
  'Hong Kong': '🇭🇰',
  'Hungary': '🇭🇺',
  'Iceland': '🇮🇸',
  'India': '🇮🇳',
  'Ireland': '🇮🇪',
  'Israel': '🇮🇱',
  'Italy': '🇮🇹',
  'Jamaica': '🇯🇲',
  'Japan': '🇯🇵',
  'Martinique': '🇲🇶',
  'Mexico': '🇲🇽',
  'Morocco': '🇲🇦',
  'Netherlands': '🇳🇱',
  'New Zealand': '🇳🇿',
  'Peru': '🇵🇪',
  'Philippines': '🇵🇭',
  'Portugal': '🇵🇹',
  'Puerto Rico': '🇵🇷',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent & the Grenadines': '🇻🇨',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Singapore': '🇸🇬',
  'Sint Maarten': '🇸🇽',
  'South Korea': '🇰🇷',
  'Spain': '🇪🇸',
  'St. Kitts & Nevis': '🇰🇳',
  'Sweden': '🇸🇪',
  'Switzerland': '🇨🇭',
  'Thailand': '🇹🇭',
  'Trinidad & Tobago': '🇹🇹',
  'United Arab Emirates': '🇦🇪',
  'United Kingdom': '🇬🇧',
  'USA': '🇺🇸',
};

export function getFlag(country: string): string {
  return COUNTRY_FLAGS[country] ?? '';
}
