/**
 * Pure helpers for the Web Share Target / File Handling inbox (/share-in).
 * The stash layout mirrors public/sw.js: Cache Storage 'ac-share-in',
 * /__share/<id>/meta.json and /__share/<id>/<n> per file.
 */

export type SharedKind = 'image' | 'pdf' | 'calendar' | 'text' | 'other';

export interface SharedFileInfo { name: string; type: string }

export interface SharedMeta {
  at: number;
  title: string;
  text: string;
  url: string;
  files: { name: string; type: string; size: number }[];
}

export const SHARE_CACHE = 'ac-share-in';

export function stashKey(id: string, part: number | 'meta.json'): string {
  return `/__share/${id}/${part}`;
}

/** Ids are generated by the service worker (base36); anything else is refused. */
export function validShareId(id: unknown): id is string {
  return typeof id === 'string' && /^[a-z0-9]{6,32}$/.test(id);
}

export function sharedKind(f: SharedFileInfo): SharedKind {
  const type = f.type.toLowerCase();
  const name = f.name.toLowerCase();
  if (type === 'application/pdf' || name.endsWith('.pdf')) return 'pdf';
  if (type.startsWith('image/') || /\.(png|jpe?g|webp|heic|heif|gif)$/.test(name)) return 'image';
  if (type === 'text/calendar' || name.endsWith('.ics')) return 'calendar';
  if (type === 'text/plain' || name.endsWith('.txt')) return 'text';
  return 'other';
}

export interface ShareActions {
  /** Can go through the boarding-pass reader. */
  pass: boolean;
  /** Can be saved as a trip file. */
  file: boolean;
  /** Can be saved as a note. */
  note: boolean;
}

/** What the inbox offers for one shared item. */
export function actionsFor(kind: SharedKind): ShareActions {
  switch (kind) {
    case 'image':
    case 'pdf': return { pass: true, file: true, note: false };
    case 'text': return { pass: false, file: true, note: true };
    case 'calendar':
    case 'other': return { pass: false, file: true, note: false };
  }
}

/** The shared text, any text file's content and the url as one note body; the url is dropped when the text already has it. */
export function noteTextFrom(m: Pick<SharedMeta, 'text' | 'url'>, fileText = ''): string {
  const text = m.text.trim();
  const url = m.url.trim();
  return [text, fileText.trim(), url && !text.includes(url) ? url : ''].filter(Boolean).join('\n\n');
}

export function noteTitleFrom(m: Pick<SharedMeta, 'title'>, fallbackName = ''): string {
  return m.title.trim() || fallbackName.replace(/\.[^.]+$/, '').trim() || 'Shared note';
}

export interface BackgroundChecksSupport { supported: boolean; reason: 'ok' | 'no-sw' | 'no-notifications' | 'no-periodic-sync' }

/** Periodic Background Sync needs a worker, notifications and the (Chromium-only) periodicSync manager. */
export function backgroundChecksSupport(env: {
  hasServiceWorker: boolean; hasNotification: boolean; registration: object | null;
}): BackgroundChecksSupport {
  if (!env.hasServiceWorker) return { supported: false, reason: 'no-sw' };
  if (!env.hasNotification) return { supported: false, reason: 'no-notifications' };
  if (!env.registration || !('periodicSync' in env.registration)) return { supported: false, reason: 'no-periodic-sync' };
  return { supported: true, reason: 'ok' };
}

export const SCHEDULE_CHECK_TAG = 'schedule-check';
export const SCHEDULE_CHECK_MIN_INTERVAL_MS = 12 * 60 * 60 * 1000;

/** Limits the service worker applies to one share (keep in sync with public/sw.js). */
export const SHARE_MAX_FILES = 5;
export const SHARE_MAX_BYTES = 25 * 1024 * 1024;
export const SHARE_TOO_LARGE_TEXT = 'That share is too big to receive. Share up to 5 files, 25 MB in all.';
export const SHARE_FAILED_TEXT = "Couldn't receive that share. Try again.";
